### ISSUE TITLE
Encrypt / Decrypt mode TEST

### ISSUE THREAD

**Issue by lopestom** [1ndev-ui/TWRP_CG65_device_tree#6]
I don't want to fork your repository. But if you want some help or want to test an img file with decryption mode enabled, just let me know so I can prepare a correct img file.
First I will try to compile something and thus try to reduce the img file.
So I'll come back to tell you if this was possible according to my information: [Encrypt_Decrypt in the 32MB reduced](https://github.com/lopestom/twrp_device_ulefone_Power_Armor14_Pro/releases/tag/Encrypt_Decrypt)

**Comment by 1ndev-ui** [comment]
I went with the route of disabling the forced ecryption of userdata. This was done by formatting/wiping userdata then flashing [DFE-NEO-2.5.1](https://mega.nz/file/D6A3FRab#GL-hQIQHpCW03mrbtBf5gzqmbnzPFS4yGOCXW_lQf7I) with TWRP/OFRP. That would make the internal storage (/data) accessable from the custom recovery without crypto libraries...

I've tried several times to enable crypto by adding various `TW_EXCLUDE_` flags to the BoardConfig.mk on the branch: [main_crypto_enabled](https://github.com/1ndev-ui/TWRP_CG65_device_tree/tree/main_crypto_enabled).
Although yes, the boot partition was still too big (around 33.9 MB). However; I did not add ALL the flags you've used so that could be helpful towards lowering the size. 

For the recovery to be bootable into Android I ported over the remaining files in the ramdisk.cpio from the TWRP_boot.img to the stock_boot.img overwriting stock files. This would obviously make the TWRP_boot.img larger although within the 32MB limt. Sometimes I would face issues after rooting with magisk because that would make the .img larger than 32 MB. 

The images I have that are in the release are both Stock & Rooted boot.img's with both TWRP & OFRP recoveries. Those fully work although no crypto support.

Thanks @lopestom for the tutorial btw, helped a lot with making this.

**Comment by 1ndev-ui** [comment]
On the branch: [main_crypto_enabled](https://github.com/1ndev-ui/TWRP_CG65_device_tree) 

Is where I've enabled crypto, have yet to add `TW_EXCLUDE_`

**Comment by lopestom** [comment]
> The images I have that are in the release are both Stock & Rooted boot.img's with both TWRP & OFRP recoveries. Those fully work although no crypto support.

You have two ways to have encryption, but one of them will be insecure (no password and open to open the data.emmc.win file).
So maybe even trying with unofficial/insecure encryption, which we did some time ago with A11 and earlier, with the firmware in version 13 may not work due to Android security changes. But that doesn't mean you can try and confirm whether it works or not. Because your device has an old board, so it would be interesting to check.
The other way would be official encryption which will depend on the size of the img file and what can be done for non-priority files.
Unfortunately, with Android 12+ and having only 32MB on the boot partition, it becomes more difficult to remove files.

There is still a third attempt, but this part is more complicated and involves resizing the partitions. I was doing tests myself to see if it would work. But due to my time, I didn't pursue the idea. Until another user with an A12 with a Tecno device asked for help and so he did something, but these devices have more cases of hash signatures in the files and thus got a black screen when starting in TWRP. So I don't recommend that now.

Finally, the insecure encryption part involves modifying the \vendor\etc\*.fstab.* file changing from _fileencryption_ to _encryptable_. It is also good to modify the *.fstab.* files in the device tree or within the twrp.img file.
When installing the vendor_mod.img file through fastbootd, do a FORMAT DATA or with original boot.img/recovery mode, Wipe Data/Factory Reset. If the device starts on Android, then there is already a 50% chance of having insecure encryption and \Data backup.

**Comment by lopestom** [comment]
@1ndev-ui 

I sent just now in your email the img for test.
Let me know what happen.

.

**Comment by 1ndev-ui** [comment]
@lopestom 

In my attempt to reflash the boot.img you sent to me, what happened was a boot loop and the /data partition was re-encrypted. Even when using fastbootd to boot into recovery partition. What was your process on building that boot.img?

**Comment by lopestom** [comment]
> Even when using fastbootd

Not use fastbootd to install boot.img file. **Use fastboot (bootloader).**

> What was your process on building that boot.img?

Normal compiling from minimal mabifest source code. But unpack img file to removing some files & changing others.
I'll send other img fle for test. But confirm the 1st file installing with fastboot (bootloader). 

Another observation:
- I got the [kernel](https://github.com/1ndev-ui/TWRP_CG65_device_tree/blob/main/prebuilt/Image.gz) from this repository/branch;
- But I also have the firmware and with the stock boot.img file, the size of the kernel files are different (10.2MB and 10.6MB). So it is necessary to confirm this too. What kernel is correctlly?!

**Comment by 1ndev-ui** [comment]
Send me both please and I will give the results for both.

**Comment by 1ndev-ui** [comment]
> Not use fastbootd to install boot.img file. **Use fastboot (bootloader).**

> Normal compiling from minimal mabifest source code. But unpack img file to removing some files & changing others.
> I'll send other img fle for test. But confirm the 1st file installing with fastboot (bootloader). 

I flashed both the a13 & a12 boot.imgs from the bootloader and both resulted in a bootloop + reencrypting the data partition. 

The second a12 boot image when booting into recovery resulted in a black screen then loop.

> - I got the [kernel](https://github.com/1ndev-ui/TWRP_CG65_device_tree/blob/main/prebuilt/Image.gz) from this repository/branch;
> - But I also have the firmware and with the stock boot.img file, the size of the kernel files are different (10.2MB and 10.6MB). So it is necessary to confirm this too. What kernel is correctlly?!

The prebuilt [kernel](https://github.com/1ndev-ui/TWRP_CG65_device_tree/blob/main/prebuilt/Image.gz) is the original prebuilt from the stock boot but compressed in .gz format. I used pigz to do this. (For saving some space)

**Comment by lopestom** [comment]
> > Not use fastbootd to install boot.img file. **Use fastboot (bootloader).**
> 
> > Normal compiling from minimal mabifest source code. But unpack img file to removing some files & changing others.
> > I'll send other img fle for test. But confirm the 1st file installing with fastboot (bootloader).
> 
> I flashed both the a13 & a12 boot.imgs from the bootloader and both resulted in a bootloop + reencrypting the data partition.
> 
> The second a12 boot image when booting into recovery resulted in a black screen then loop.
> 
> > * I got the [kernel](https://github.com/1ndev-ui/TWRP_CG65_device_tree/blob/main/prebuilt/Image.gz) from this repository/branch;
> > * But I also have the firmware and with the stock boot.img file, the size of the kernel files are different (10.2MB and 10.6MB). So it is necessary to confirm this too. What kernel is correctlly?!
> 
> The prebuilt [kernel](https://github.com/1ndev-ui/TWRP_CG65_device_tree/blob/main/prebuilt/Image.gz) is the original prebuilt from the stock boot but compressed in .gz format. I used pigz to do this. (For saving some space)

The boot-CG65-A12-20240508.img has kernel file 10.6MB
If you can so use the kernel file that work in your device for confirmation.

However, I still see that you may be right why we will not be able to reduce the size of the img file without losing something related to encryption due to the new TWRP source code having more files and of significant size.

Another idea would be to have the TWRP source code before these changes, if I'm not mistaken when I did TWRP [here](https://github.com/lopestom/twrp_device_ulefone_Power_Armor14_Pro/releases) on Dec 29, 2023 with a 31.4 MB file, there weren't so many changes and files that would hinder the reduction process. But I don't know if you have a great computer to do anything.

Even so, I'm going to use the 10.2MB kernel and still check what can be done. Unfortunately in this last img file, I removed a 1.2MB binary file that I don't know if it is essential for decryption/for the device and that's why it has a black screen.

Well, let's try until we're sure there's a chance. If it had TWRP LOGO I would say we would be close.

**Comment by 1ndev-ui** [comment]
I've been using a cloud server to build. It's got a 4.1Ghz 8 core Intel CPU, 32GB of RAM & a 2TB NVMe SSD.

Whenever I make changes to the extracted ramdisk.cpio manually I found that I have to update the ramdisk-files.txt & ramdisk-files.sha256sum so that the recovery can include the changed files and new files to the ramdisk.

I used these commands to generate a new sha256 list from the extracted ramdisk directory before repacking:

`rm ramdisk-files.txt && rm ramdisk-files.sha256sum`

`find . -type f -print0 | xargs -0 ls >> ramdisk-files.tmp`

`sed 's/..//' ramdisk-files.tmp >> ramdisk-files.txt`

`rm ramdisk-files.tmp`

`find . -type f -print0 | xargs -0 sha256sum >> ramdisk-files.sha256sum`

Then it got me thinking if it is possible to build JUST the encryption libraries and dependencies without actually including it into the boot.img. That way we can inject the crypto stuff into the ramdisk/boot.img that is currently stable/bootable.

**Comment by lopestom** [comment]
> Then it got me thinking if it is possible to build JUST the encryption libraries and dependencies without actually including it into the boot.img. That way we can inject the crypto stuff into the ramdisk/boot.img that is currently stable/bootable.

If you increased the boot size on the DT to 40MB - enabled encryption - highlighted the correct files for the decryption type - and compiled the img file, just send me that file so I can analyze which files can be removed.

The big problem with having online servers is the particularity of cloning the general TeamWin repository. Using the minimal manifest will always direct you to the most up-to-date TWRP repository.
But other users even on github have forked the android_bootable_recovery repository before the changes. So either you do something on your computer with the old repository or you know how to make the compilation script pick up the repopick of those changes.

Do you have experience with programming/scripts?
For those who don't have many resources or knowledge, it becomes more difficult.

**Comment by 1ndev-ui** [comment]
> If you increased the boot size on the DT to 40MB - enabled encryption - highlighted the correct files for the decryption type - and compiled the img file, just send me that file so I can analyze which files can be removed.

Okay, I'll take a shot at that now...
I changed:

BOARD_BOOTIMAGE_PARTITION_SIZE :=  33554432

To:

BOARD_BOOTIMAGE_PARTITION_SIZE :=  41943040

On the main_crypto_enabled branch. 

I'm using an Actions to build, here is the [log](https://github.com/1ndevelopment/Action-Recovery-Builder/actions/runs/9037245101)

> The big problem with having online servers is the particularity of cloning the general TeamWin repository. Using the minimal manifest will always direct you to the most up-to-date TWRP repository.
> But other users even on github have forked the android_bootable_recovery repository before the changes. 

Do you know what version TWRP was before _those_ changes were implemented?

> Do you have experience with programming/scripts?

Yes I do have experience with scripting and some programming languages. (Bash, python, some C & .yaml)

**Comment by 1ndev-ui** [comment]
This device uses microtrust beanpod so unsure what libraries to compile, so I will build all of them first.

---

> If you increased the boot size on the DT to 40MB - enabled encryption - highlighted the correct files for the decryption type - and compiled the img file, just send me that file so I can analyze which files can be removed.

First I compiled the [Device Tree](https://github.com/1ndev-ui/TWRP_CG65_device_tree/tree/main_crypto_enabled) with the increased 40MB (41943040 bytes) boot partition while enabling the: `TW_INCLUDE_CRYPTO := true` flag.

Here is the [build log](https://github.com/1ndevelopment/Action-Recovery-Builder/actions/runs/9037245101) and the [release](https://github.com/1ndevelopment/Action-Recovery-Builder/releases/tag/9037245101).

Then unpacked the [non-rooted crypto included boot.img](https://github.com/1ndevelopment/Action-Recovery-Builder/releases/tag/9037245101) ramdisk and merged it to the [non-rooted non-crypto boot.img](https://github.com/1ndev-ui/TWRP_CG65_device_tree/releases/tag/24ww13.7) ramdisk. 

Finally re-compressed the ramdisk.cpio & repacked using:

`find . | cpio -o -H newc > ../ramdisk.cpio`

`magiskboot repack ../VORTEX_CG65_TWRP_STOCK_BOOT_A.03-31-24.img`


Afterward, the [VORTEX_CG65_TWRP_CRYPTO_STOCK_BOOT_A.5-10-24.img](https://mega.nz/file/HnRF3LIC#0VdXO0EwbQey6p2fPROPRCOb8FpUJdIvyRwSBUN84hQ) which has the crypto libraries was created. 34.37MB (36040704 bytes)

That's 2.37MB (2486272 bytes) larger than the intended 32MB (33554432 bytes).

When you have the free time I'd appreciate it if you could compare the [non-rooted non-crypto boot.img 32MB](https://github.com/1ndev-ui/TWRP_CG65_device_tree/releases/tag/24ww13.7) to the [non-rooted crypto included boot.img 34MB](https://mega.nz/file/HnRF3LIC#0VdXO0EwbQey6p2fPROPRCOb8FpUJdIvyRwSBUN84hQ).


Both kernels in the compressed boot images are 25MB (26075136 bytes). Keep in mind that the boot.img is a tad bit bigger once the Magisk patch is introduced. (About 0.51MB larger, 532480 bytes)

---

> The big problem with having online servers is the particularity of cloning the general TeamWin repository. Using the minimal manifest will always direct you to the most up-to-date TWRP repository.
> But other users even on github have forked the android_bootable_recovery repository before the changes. 

Do you know what version TWRP was before _those_ changes were implemented?

> Do you have experience with programming/scripts?

Yes I do have experience with scripting and some programming languages. (Bash, python, some C & .yaml)

**Comment by lopestom** [comment]
> Do you know what version TWRP was before _those_ changes were implemented?

https://github.com/TeamWin/android_bootable_recovery/commits/android-12.1/?before=a28a9f3867483fb5026601d954a3bf9059886b71+35

![ksnip_20240510-191808](https://github.com/1ndev-ui/TWRP_CG65_device_tree/assets/25868008/54d7e708-0cca-4c6e-910f-284d9c5e5b90)

> Do you know what version TWRP was before _those_ changes were implemented?

The version of TWRP in that is 3.7.0_12
Actually the version is 3.7.1_12

>I used Actions to build, here is the [log](https://github.com/1ndevelopment/Action-Recovery-Builder/actions/runs/9037245101) and here is the [release](https://github.com/1ndevelopment/Action-Recovery-Builder/releases/tag/9037245101).
> 34.37MB (36040704 bytes)
> 
> That's 2.37MB (2486272 bytes) larger than the intended 32MB (33554432 bytes).

Your boot.img Crypt file has `bash` included. More files and size........ 3MB +
With only 32MB inthe partition so cannot choice `tools`.

> Yes I do have experience with scripting and some programming languages. (Bash, python, some C & .yaml)

May be we can make the script for mount (ro or rw) the \vendor (not of TWRP) and call the folders\files.
I have work slowly with that. Not tested yet. I have TWRP working so I really not need. But thinking for others....

**Comment by 1ndev-ui** [comment]
> Your boot.img Crypt file has `bash` included. More files and size........ 3MB +
> With only 32MB inthe partition so cannot choice `tools`.

Those tools must have been left over from [this build](https://github.com/1ndevelopment/Action-Recovery-Builder/actions/runs/8499387738). 

I'll recompile the main_crypto_enabled branch again with:

`TW_EXCLUDE_TWRPAPP := true`
`TW_EXCLUDE_PYTHON := true`
`TW_EXCLUDE_TZDATA := true`
`TW_EXCLUDE_BASH := true`

Here is the [release](https://github.com/1ndevelopment/Action-Recovery-Builder/releases/tag/9039184547).

And port it over to the stock_boot.img ramdisk and recompress. 

> May be we can make the script for mount (ro or rw) the \vendor (not of TWRP) and call the folders\files.

If I remember correctly the vendor partition is merged into the super.img. So unpacking the vendor.img & adding files, then repacking it into the new_super.img would be useful to store the extra files/folders needed for decryption from recovery. 

One way to do this is by using `simg2img` to convert the compressed super.img (About 4GB) to raw_super.img (About 8GB), then using something like `lpunpack` to unpack all the partitions from the raw_super.img. This would allow for mounting the vendor.img as read/write, thus gaining the ability to add the needed decryption libraries, then following that up with unmounting the vendor.img & creating a new_super.img with `lpmake`.

That seems rather daunting considering that the decryption libraries would have to be pulled from the vendor partition into the recovery boot partition at boot. Then unmounted at recovery and a new_super.img would have to be flashed as well (About 4GB). 

That being said that would give us the ability to add the necessary decryption libraries to the boot.img partition from the vendor.img partition although it's quite a process...

The next question is; do you know anyway to inject files from the vendor into the custom recovery at boot? Before any of the TWRP stuff is loaded?

**Comment by lopestom** [comment]
> Those tools must have been left over from [this build](https://github.com/1ndevelopment/Action-Recovery-Builder/actions/runs/8499387738).

https://productionresultssa8.blob.core.windows.net/actions-results/9600469b-23b7-4199-8767-dbaff2d0b15b/workflow-job-run-ca395085-040a-526b-2ce8-bdc85f692774/logs/job/job-logs.txt?rsct=text%2Fplain&se=2024-05-11T00%3A46%3A07Z&sig=TWvnPLq3t9o590SA4MuZfy2VsK7cj03qSPtJCHa1MDA%3D&sp=r&spr=https&sr=b&st=2024-05-11T00%3A36%3A02Z&sv=2021-12-02
```
ut/target/product/CG65/gen/META/lic_intermediates/out/target/product/CG65/obj/EXECUTABLES/bash_intermediates/bash.meta_module
2024-03-31T16:22:05.5974009Z [ 22% 5109/23216] build out/target/product/CG65/gen/META/lic_intermediates/out/target/product/CG65/system/system_ext/bin/bash.meta_module
2024-03-31T16:22:05.6032929Z [ 22% 5110/23216] build out/target/product/CG65/gen/META/lic_intermediates/libtilde.meta_lic
2024-03-31T16:22:05.6059212Z [ 22% 5111/23216] build out/target/product/CG65/gen/META/lic_intermediates/out/target/product/CG65/system/system_ext/etc/bash/bash_logout.meta_module
2024-03-31T16:22:05.6104103Z [ 22% 5112/23216] build out/target/product/CG65/gen/META/lic_intermediates/out/target/product/CG65/system/system_ext/etc/bash/bashrc.meta_module
2024-03-31T16:22:05.6127054Z [ 22% 5113/23216] build out/target/product/CG65/gen/META/lic_intermediates/out/target/product/CG65/system/system_ext/etc/bash/inputrc.meta_module
2024-03-31T16:22:05.6170379Z [ 22% 5114/23216] build out/target/product/CG65/gen/META/lic_intermediates/out/target/product/CG65/obj/FAKE/bash_twrp_intermediates/bash_twrp-timestamp.meta_module
2024-03-31T16:22:05.6243800Z [ 22% 5115/23216] build out/target/product/CG65/gen/META/lic_intermediates/out/target/product/CG65/root/system/bin/bash_twrp-timestamp.meta_module
```

> If I remember correctly the vendor partition is merged into the super.img. So unpacking the vendor.img & adding files, then repacking it into the new_super.img would be useful to store the extra files/folders needed for decryption from recovery.
> 
> One way to do this is by using `simg2img` to convert the compressed super.img (About 4GB) to raw_super.img (About 8GB), then using something like `lpunpack` to unpack all the partitions from the raw_super.img. This would allow for mounting the vendor.img as read/write, thus gaining the ability to add the needed decryption libraries, then following that up with unmounting the vendor.img & creating a new_super.img with `lpmake`.
> 
> That seems rather daunting considering that the decryption libraries would have to be pulled from the vendor partition into the recovery boot partition at boot. Then unmounted at recovery and a new_super.img would have to be flashed as well (About 4GB).

It's not that. Having the subpartitions in RW is very, very easy for me. Mainly using Linux!
Obviously having a super_mod.img in rw is not difficult, and so is the part of mounting \vendor so that it can be referenced as a symlink with:
`
/vendor             ext4    /dev/block/mapper/vendor 
`

> That being said that would give us the ability to add the necessary decryption libraries to the boot.img partition from the vendor.img partition although it's quite a process...

The problem for you is just one file: `/vendor/thh/ta/c09c9c5daa504b78b0e46eda61556c3a.ta`

For me there are 2 files, one 1.8MB and the other 2.1MB. But the kernel is 9.9MB, and yours is 10.2~10.6MB.

With TWRP v3.7.1_12, then everything for your device is significantly bad. If you unpack the boot.img files I sent you, then you will see the decryption files. They are there and it just won't work due to the inability to interact with other necessary files in \system\bin & \lib64 which are files of sizes beyond what would be useful.
I say this because v3.7.0_12 works and the files are smaller or there is no addition of files like in v3.7.1_12
**

> The next question is; do you know anyway to inject files from the vendor into the custom recovery at boot? Before any of the TWRP stuff is loaded?

See and compare the files I sent you!
Not everything I wrote [here](https://github.com/lopestom/twrp_device_ulefone_Power_Armor14_Pro/releases/tag/Encrypt_Decrypt). But I left some very simple clues.

---------------

The repacked bootTWRP-Crypt.img is no good: 33,2 MB (34.779.136)
The problem: kernel and c09c9c5daa504b78b0e46eda61556c3a.ta files sizes.

I'll look more. Need time.

**Comment by lopestom** [comment]
> I'll recompile the main_crypto_enabled branch again with:
> 
> `TW_EXCLUDE_TWRPAPP := true` `TW_EXCLUDE_PYTHON := true` `TW_EXCLUDE_TZDATA := true` `TW_EXCLUDE_BASH := true`
> 
> Here is the [release](https://github.com/1ndevelopment/Action-Recovery-Builder/releases/tag/9039184547).

If you unpack the img file you'll see:
![ksnip_20240511-111915](https://github.com/1ndev-ui/TWRP_CG65_device_tree/assets/25868008/e29b2fc6-b453-4de7-9e64-6c148b59b5e7)


So the files has more than 3.0MB
I compiled img file and not have that. Maybe you're using other flag tah call bash files.

**Comment by lopestom** [comment]
Okay, my 
## conclusion about

1. The kernel file has (10.2MB ~ 10.6MB);
2. The file c09c9c5daa504b78b0e46eda61556c3a.ta has 2.14 MB;
https://github.com/1ndev-ui/dump_vortex_CG65/blob/c3ee2b89303eec6b3c14eae9a55fbea245c888a1/vendor/thh/ta/c09c9c5daa504b78b0e46eda61556c3a.ta

Both files is no good with new 3.7.1_12 version since the TeamWin source code has more files too.
I don't know if the .ta file is needed for decryption permissions - PIN or if it is for fingerprint or for everything. In this sense, compiling the img file with it, but unpacking the img file and removing it to repackage and testing this img file to confirm the doubt, is something you can do yourself.

3. I got a reduced img file with 32.5MB but maybe no good to start and without internal tools;
4. Even with all attempts, the device may still have a TWRP logo.

- Final conclusion
With version 3.7.1_12 it will not be possible to have an img file smaller than 32MB. If the kernel had a size between 9MB and 10MB, that would be more interesting and would give a chance to reduce the img file, perhaps to 31.9MB.

## Testing the modified vendor.img => vendor_Mod.img
Need unpack stock vendor.img file and after modified file so repack to img again. Has very tools for that in the Linux or Win10_11(WSL).

### Changing fstab file
Here 
https://github.com/1ndev-ui/dump_vortex_CG65/blob/c3ee2b89303eec6b3c14eae9a55fbea245c888a1/vendor/etc/fstab.mt6765#L19

Modify the line
`fileencryption=aes-256-xts:aes-256-cts:v2,keydirectory=/metadata/vold/metadata_encryption`
to
`encryptable=/dev/block/by-name/userdata`

I have a MT6768 device with A12 and it worked because of the old kernel.
So I don't know if it will work for you.
Some extra information: [4pda - INSTRUCTIONS FOR DISABLED DATA ENCRYPTION](https://4pda.to/forum/index.php?showtopic=1028983&view=findpost&p=115853116)

[4pda - My MT6768 A12 NoCrypt](https://4pda.to/forum/index.php?showtopic=1034699&view=findpost&p=118997965)

[4pda - My MT6762_65 A11 NoCrypt](https://4pda.to/forum/index.php?act=findpost&pid=115628871&anchor=Spoil-115628871-1)

If it doesn't work, you may need to change all the fstab files in Custom Recovery as well.
Everything will be trial and error to confirm possibilities. But even so, there will be a case where you won't be able to do so due to Android's new security policies.

Good lucky
